### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by zyllorion** [Emerson/ember-form-master-2000#11]
Hi,
```
for: null,
```
in fm-form is breaking IE8 compatibility.  Please can you refactor?

Thank you!

**Comment by Emerson** [comment]
I'll look at this soon - somehow did not have notifications turned on for this repo!

**Comment by Emerson** [comment]
Hey man - know you already moved away from this lib, but thanks for filing the issue! Sorry for not catching this sooner.

Should be resolved now.
