### ISSUE TITLE
glimmer Time!

### ISSUE THREAD

**Issue by OpakAlex** [Emerson/ember-form-master-2000#18]

**Comment by OpakAlex** [comment]
what about update to glimmer?

**Comment by Emerson** [comment]
Working on it :-)

**Comment by Emerson** [comment]
Things are still pretty broken in the current beta release. I've done some initial updates on a glimmer branch [here](https://github.com/Emerson/ember-form-master-2000/tree/feature/glimmer), but there are enough issues that it doesn't make sense for me to invest my time until some of the issues are resolved.

**Comment by OpakAlex** [comment]
Yes, i have too problem with this... my tests broken(

**Comment by blimmer** [comment]
I've got this working with the current 1.13 (glimmer) beta on my PR #21
