### ISSUE TITLE
Difficult to integration test components that use an fm-form

### ISSUE THREAD

**Issue by blimmer** [Emerson/ember-form-master-2000#19]
With the new [component integration tests](https://github.com/switchfly/ember-test-helpers/pull/38), it's easier to give a component access to a container for testing. However, the current way the initializer is set up, it requires an `application` to be present, which isn't available in a unit test.

I think this could be solved by using an [instance-initializer](http://emberjs.com/blog/2015/05/13/ember-1-12-released.html#toc_instance-initializers) and calling `register` and `injection` on the `instance` that gets passed through. For instance, check out how [ember-i18n](https://github.com/jamesarosen/ember-i18n/blob/master/app/instance-initializers/ember-i18n.js#L17) does this.

The thing that I'm not sure about is how you could make this backwards compatible for pre 1.12 Ember apps.

**Comment by Emerson** [comment]
Hmm, I'll look into this, but the documentation seems a little thin right now. Also not sure the best way to maintain backwards compatibility.

**Comment by blimmer** [comment]
In Ember I18n he has [both](https://github.com/jamesarosen/ember-i18n/blob/master/app/initializers/ember-i18n.js) an `initializer` and an `instance-initializer` (the `initializer` flavor just imports and calls the `instance-intiailizer`). I think this is how he manages backwards compatibility.

**Comment by Emerson** [comment]
Think this issue is resolved! Moved the latest version over to a service based approach for customizations. Would love to know if this made your life easier _(if you're still even using this library)_
