### ISSUE TITLE
Publish 0.2.0

### ISSUE THREAD

**Issue by blimmer** [Emerson/ember-form-master-2000#22]
Now that 1.13 is live, it would be nice to take advantage of the deprecation fixes in master.

**Comment by Emerson** [comment]
Agreed 100% and realize I've been a little absent over the last little bit. Heading down to Boston for the week _(attending Wicked Good Ember)_, but plan to be back on top of this stuff soon after.

Just loaded up your recent changes on `master`. Do you think it's worth publishing to NPM as 0.2.0? _(I'll do it now)_

**Comment by blimmer** [comment]
I think 0.2.0 is ready to go now that 1.13 is the latest release. Nice to
not be the deprecation offender on an ember build!

On Sun, Jun 14, 2015 at 3:43 PM, Emerson Lackey <notifications@github.com>
wrote:

> Agreed 100% and realize I've been a little absent over the last little
> bit. Heading down to Boston for the week *(attending Wicked Good Ember)*,
> but plan to be back on top of this stuff soon after.
>
> Just loaded up your recent changes on master. Do you think it's worth
> publishing to NPM as 0.2.0? *(I'll do it now)*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emerson/ember-form-master-2000/issues/22#issuecomment-111878139>
> .
>



-- 
*Ben Limmer*
Software Developer
ben@ibotta.com

**Comment by Emerson** [comment]
Just to confirm, are you seeing these as well when using Ember 1.13.0?

![deprecations](https://cloud.githubusercontent.com/assets/186545/8150593/6c5afd66-12bd-11e5-9ccf-f577a7c5e945.gif)

**Comment by blimmer** [comment]
There's definitely some additional work to squash all deprecations, but we've got all template compile-time bugs fixed in master right now.

**Comment by Emerson** [comment]
Great! I'll publish 2.0 now. Just wanted to make sure I wasn't missing something. Thanks for all the work on this, really nice to have another pair of eyes on things.

**Comment by blimmer** [comment]
No problem!

On Sun, Jun 14, 2015 at 3:57 PM, Emerson Lackey <notifications@github.com>
wrote:

> Great! I'll publish 2.0 now. Just wanted to make sure I wasn't missing
> something. Thanks for all the work on this, really nice to have another
> pair of eyes on things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emerson/ember-form-master-2000/issues/22#issuecomment-111878786>
> .
>



-- 
*Ben Limmer*
Software Developer
ben@ibotta.com

**Comment by Emerson** [comment]
![pushed](https://cloud.githubusercontent.com/assets/186545/8150638/40983840-12bf-11e5-9509-e9b6a1ef9d20.png)

**Comment by blimmer** [comment]
Thanks!
