### ISSUE TITLE
Ember 2.0 Helpers

### ISSUE THREAD

**Issue by lifeart** [Emerson/ember-form-master-2000#29]
in 
* addon/helpers/*.js

```export default Ember.Handlebars.makeBoundHelper(isNotHelper);```
=>>
```export default Ember.Helper.helper(isNotHelper);```

(error makeboundhelper deprecated)

**Comment by Emerson** [comment]
Do we just need to update to the new syntax?

```
export default Ember.Helper.helper(isNotHelper);
```

**Comment by Emerson** [comment]
I think this has been resolved in the most recent release! Thanks for the heads up
