### ISSUE TITLE
Better documentation for initializers

### ISSUE THREAD

**Issue by Emerson** [Emerson/ember-form-master-2000#3]
Create an initializer and documentation that works with the foundation CSS framework

**Comment by blimmer** [comment]
What's the vision for this? Is it to build a switch in the dummy app to change out the config? Is it just to provide documentation and not a running example?

**Comment by jelhan** [comment]
Since configuration is now handled by a service `beforeModel` or `afterModel` hook of application route should be used or? Initializer seems to be outdated.

**Comment by g-cassie** [comment]
Closing.  All config can now be done by overriding the service.
