### ISSUE TITLE
Documentation/support for 422 field level validation errors

### ISSUE THREAD

**Issue by zyllorion** [Emerson/ember-form-master-2000#8]
Ember Canary
Ember Data beta 15

I retrieve errors back from the server in what seems to be the recommended way:

```
        res.status(422).send({
            "errors": {
                "field_one": ["error 1", "error 2"],
                "field_two": ["error 1"],
                "serviceNotification": ["A problem with serviceNotification"]
            }
        });
```
... along with an implementation for `RESTAdapter.ajaxError` from http://alexspeller.com/server-side-validations-with-ember-data-and-ds-errors/ which populates the records errors object.  In inspector for the record that's put, $E.get('errors.content') returns an array of 4 error objects with an attribute and message for each.

My template has something like:
```
{{fm-checkbox label=(t 'some_translation') checked=model.myModel.theField errors=model.myModel.errors.theField.message}}
```
This example doesn't work, but model.myModel.errors.theField does (however it displays [object Object] as the error).  In the example above there would be two errors for one of the fields, held as two separate objects in the errors.content.

Not sure if you have a different implementation for errors or I'm just addressing it incorrectly within the template?

I'll reference https://github.com/emberjs/data/issues/2028 because it has related information.
Also http://emberjs.jsbin.com/sidarufuco/1/edit?html,css,js,output as an example that shows multiple errors.

Hope that's enough information!

Thanks

**Comment by petermumford** [comment]
@zyllorion did you find a solution to this? I am getting the same issue as you.

**Comment by zyllorion** [comment]
@petermumford I've actually removed any dependency on this npm for this and ie8 reasons.  I wrote my own components in the end.

**Comment by Emerson** [comment]
Sorry for missing this guys - Was not subscribed to the issues. I'll be addressing this as soon as possible and have turned on notifications!

**Comment by petermumford** [comment]
@Emerson To get this working for me I changed the `error` function in `fm-errortext.js` to the below:

    if (Ember.isArray(this.get('errors'))) {
      return this.get('errors.firstObject');
    } else {
      return this.get('errors');
    }

Originally the code was looking for an array and I was passing in an object, hence the strange output. So now I'm simply checking if the object is an array.

**Comment by Emerson** [comment]
Really appreciate the feedback and code. I've gone ahead and added this _(and another error case)_ to core and it's available as an update through NPM now. 

Let me know if you try to update - I recently upgraded the project to use Ember-CLI latest, which moved to HTML bars.

Thanks again!

**Comment by petermumford** [comment]
Looks great. Thank you.
